### ISSUE TITLE
Search bar text is unclear in dark mode

### ISSUE THREAD

**Issue by tpps88206** [candy02058912/search-sketch#1]
When using dark mode in Sketch, the background color is dark gray and text in the search bar is black.

This makes it difficult for users to see the text clearly.

<img width="644" alt="截圖 2020-02-27 上午10 34 40" src="https://user-images.githubusercontent.com/24426130/75407150-3c76e480-594d-11ea-917a-ed9489303764.png">

**Comment by candy02058912** [comment]
It should look like this afterwards 😄 
<img width="632" alt="Screen Shot 2020-03-01 at 10 53 48 AM" src="https://user-images.githubusercontent.com/6586048/75618549-f4ed9400-5baa-11ea-95f9-80113d7336d3.png">
![image](https://user-images.githubusercontent.com/6586048/75618554-12baf900-5bab-11ea-8064-fb72cb255161.png)
